// code[0] maps to master_matkul.kode_aktif; the rest map to kode_alias.
export const kurikulum2023Nodes = [
  // Semester 1
  {
    id: 1,
    code: ["AIF231101"],
    label: "Matematika Dasar",
    sks: 4,
    semester: 1,
    kolom: 4,
    tipe: "wajib",
  },
  {
    id: 2,
    code: ["AIF231103", "AIF181101"],
    label: "Dasar Pemrograman",
    sks: 4,
    semester: 1,
    kolom: 7,
    tipe: "wajib",
  },
  {
    id: 3,
    code: ["AIF231105", "AIF181107"],
    label: "Matematika Diskret",
    sks: 4,
    semester: 1,
    kolom: 5,
    tipe: "wajib",
  },
  {
    id: 4,
    code: ["MKU230110"],
    label: "Pendidikan Kewarganegaraan",
    sks: 2,
    semester: 1,
    kolom: 1,
    tipe: "wajib",
  },
  {
    id: 5,
    code: ["MKU230120"],
    label: "Bahasa Indonesia",
    sks: 2,
    semester: 1,
    kolom: 3,
    tipe: "wajib",
  },
  {
    id: 6,
    code: ["MKU230130"],
    label: "Logika",
    sks: 2,
    semester: 1,
    kolom: 2,
    tipe: "wajib",
  },

  // Semester 2
  {
    id: 7,
    code: ["AIF231104"],
    label: "Algoritma dan Pemrograman",
    sks: 4,
    semester: 2,
    kolom: 11,
    tipe: "wajib",
  },
  {
    id: 8,
    code: ["AIF231106"],
    label: "Logika Informatika",
    sks: 3,
    semester: 2,
    kolom: 4,
    tipe: "wajib",
  },
  {
    id: 9,
    code: ["AIF231202"],
    label: "Arsitektur dan Organisasi Komputer",
    sks: 4,
    semester: 2,
    kolom: 6,
    tipe: "wajib",
  },
  {
    id: 10,
    code: ["AIF231402"],
    label: "Statistika untuk Komputasi",
    sks: 3,
    semester: 2,
    kolom: 8,
    tipe: "wajib",
  },
  {
    id: 11,
    code: ["MKU230140"],
    label: "Pendidikan Pancasila",
    sks: 2,
    semester: 2,
    kolom: 2,
    tipe: "wajib",
  },
  {
    id: 12,
    code: ["MKU230150"],
    label: "Etika Dasar",
    sks: 2,
    semester: 2,
    kolom: 1,
    tipe: "wajib",
  },

  // Semester 3
  {
    id: 13,
    code: ["AIF232101", "AIF181106"],
    label: "Matriks dan Ruang Vektor",
    sks: 2,
    semester: 3,
    kolom: 2,
    tipe: "wajib",
  },
  {
    id: 14,
    code: ["AIF232103"],
    label: "Pemrograman Berorientasi Objek",
    sks: 4,
    semester: 3,
    kolom: 11,
    tipe: "wajib",
  },
  {
    id: 15,
    code: ["AIF232105"],
    label: "Struktur Diskret",
    sks: 3,
    semester: 3,
    kolom: 5,
    tipe: "wajib",
  },
  {
    id: 16,
    code: ["AIF232107"],
    label: "Algoritma dan Struktur Data",
    sks: 4,
    semester: 3,
    kolom: 9,
    tipe: "wajib",
  },
  {
    id: 17,
    code: ["AIF232201"],
    label: "Sistem Operasi",
    sks: 3,
    semester: 3,
    kolom: 6,
    tipe: "wajib",
  },
  {
    id: 18,
    code: ["MKU230180"],
    label: "Estetika",
    sks: 2,
    semester: 3,
    kolom: 1,
    tipe: "wajib",
  },

  // Semester 4
  {
    id: 19,
    code: ["AIF232002"],
    label: "Teknik Presentasi",
    sks: 2,
    semester: 4,
    kolom: 1,
    tipe: "wajib",
  },
  {
    id: 20,
    code: ["AIF232102"],
    label: "Analisis dan Desain Perangkat Lunak",
    sks: 2,
    semester: 4,
    kolom: 12,
    tipe: "wajib",
  },
  {
    id: 21,
    code: ["AIF232104"],
    label: "Desain dan Analisis Algoritma",
    sks: 4,
    semester: 4,
    kolom: 5,
    tipe: "wajib",
  },
  {
    id: 22,
    code: ["AIF232202"],
    label: "Jaringan Komputer",
    sks: 4,
    semester: 4,
    kolom: 6,
    tipe: "wajib",
  },
  {
    id: 23,
    code: ["AIF232301"],
    label: "Manajemen Informasi dan Basis Data",
    sks: 4,
    semester: 4,
    kolom: 10,
    tipe: "wajib",
  },
  {
    id: 24,
    code: ["MKU230160"],
    label: "Pendidikan Agama Katolik",
    sks: 2,
    semester: 4,
    kolom: 2,
    tipe: "wajib",
  },
  {
    id: 25,
    code: ["MKU230170"],
    label: "Fenomenologi Agama",
    sks: 2,
    semester: 4,
    kolom: 3,
    tipe: "wajib",
  },

  // Semester 5
  {
    id: 26,
    code: ["AIF233101"],
    label: "Rekayasa Perangkat Lunak",
    sks: 4,
    semester: 5,
    kolom: 15,
    tipe: "wajib",
  },
  {
    id: 27,
    code: ["AIF233401"],
    label: "Pengantar dan Aplikasi Data Science",
    sks: 3,
    semester: 5,
    kolom: 7,
    tipe: "wajib",
  },
  {
    id: 28,
    code: ["AIF182308"],
    label: "Pengantar Sistem Informasi",
    sks: 3,
    semester: 5,
    kolom: 11,
    tipe: "wajib",
  },
  {
    id: 29,
    code: ["AIF233103"],
    label: "Keamanan Informasi",
    sks: 3,
    semester: 5,
    kolom: 9,
    tipe: "wajib",
  },
  {
    id: 30,
    code: ["AIF233105"],
    label: "Artificial Intelligence",
    sks: 4,
    semester: 5,
    kolom: 4,
    tipe: "wajib",
  },
  {
    id: 31,
    code: ["AIF233107"],
    label: "Desain Antarmuka Grafis",
    sks: 2,
    semester: 5,
    kolom: 14,
    tipe: "wajib",
  },
  {
    id: 32,
    code: ["AIF233201"],
    label: "Pemrograman Berbasis Web",
    sks: 3,
    semester: 5,
    kolom: 10,
    tipe: "wajib",
  },
  {
    id: 33,
    code: ["AIF233301"],
    label: "Manajemen Proyek",
    sks: 2,
    semester: 5,
    kolom: 13,
    tipe: "wajib",
  },

  // Semester 6
  {
    id: 34,
    code: ["AIF233002"],
    label: "Sosioinformatika dan Profesionalisme",
    sks: 3,
    semester: 6,
    kolom: 1,
    tipe: "wajib",
  },
  {
    id: 35,
    code: ["AIF233102"],
    label: "Machine Learning",
    sks: 3,
    semester: 6,
    kolom: 4,
    tipe: "wajib",
  },
  {
    id: 36,
    code: ["AIF183310"],
    label: "Proyek Data Science 1",
    sks: 3,
    semester: 6,
    kolom: 7,
    tipe: "wajib",
  },
  {
    id: 37,
    code: ["AIF183308"],
    label: "Proyek Sistem Informasi 1",
    sks: 3,
    semester: 6,
    kolom: 16,
    tipe: "wajib",
  },

  // Semester 7
  {
    id: 38,
    code: ["AIF234001"],
    label: "Tugas Akhir 1",
    sks: 3,
    semester: 7,
    kolom: 1,
    tipe: "wajib",
  },
  {
    id: 39,
    code: ["AIF234101"],
    label: "Proyek Informatika",
    sks: 3,
    semester: 7,
    kolom: 14,
    tipe: "wajib",
  },
  {
    id: 40,
    code: ["AIF184303"],
    label: "Proyek Sistem Informasi 2",
    sks: 3,
    semester: 7,
    kolom: 11,
    tipe: "wajib",
  },
  {
    id: 41,
    code: ["AIF234401"],
    label: "Proyek Data Science 2",
    sks: 3,
    semester: 7,
    kolom: 7,
    tipe: "wajib",
  },

  // Semester 8
  {
    id: 42,
    code: ["AIF234002"],
    label: "Tugas Akhir 2",
    sks: 6,
    semester: 8,
    kolom: 1,
    tipe: "wajib",
  },
];
