import { EDGE_RELATION_TYPES } from "./edgeRelationTypes.js";

// sourceId and targetId map to master_matkul_edge.source_id/target_id.
export const kurikulum2023Edges = [
  {
    id: 1,
    sourceId: 2,
    targetId: 27,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS,
  },
  {
    id: 2,
    sourceId: 10,
    targetId: 27,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 3,
    sourceId: 7,
    targetId: 14,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 4,
    sourceId: 7,
    targetId: 16,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 5,
    sourceId: 9,
    targetId: 17,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS,
  },
  {
    id: 6,
    sourceId: 14,
    targetId: 20,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 7,
    sourceId: 14,
    targetId: 23,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 8,
    sourceId: 14,
    targetId: 28,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 9,
    sourceId: 16,
    targetId: 17,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH_ATAU_TEMPUH_BERSAMA,
  },
  {
    id: 10,
    sourceId: 16,
    targetId: 23,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 11,
    sourceId: 16,
    targetId: 29,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 12,
    sourceId: 16,
    targetId: 21,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS,
  },
  {
    id: 13,
    sourceId: 17,
    targetId: 22,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS,
  },
  {
    id: 14,
    sourceId: 15,
    targetId: 21,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS,
  },
  {
    id: 15,
    sourceId: 19,
    targetId: 38,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS,
  },
  {
    id: 16,
    sourceId: 20,
    targetId: 33,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 17,
    sourceId: 20,
    targetId: 31,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 18,
    sourceId: 20,
    targetId: 26,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 19,
    sourceId: 23,
    targetId: 32,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 20,
    sourceId: 23,
    targetId: 28,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 21,
    sourceId: 33,
    targetId: 39,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 22,
    sourceId: 26,
    targetId: 37,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 23,
    sourceId: 26,
    targetId: 39,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 24,
    sourceId: 27,
    targetId: 36,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 25,
    sourceId: 28,
    targetId: 40,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH_ATAU_TEMPUH_BERSAMA,
  },
  {
    id: 26,
    sourceId: 30,
    targetId: 35,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_TEMPUH,
  },
  {
    id: 27,
    sourceId: 36,
    targetId: 41,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS,
  },
  {
    id: 28,
    sourceId: 37,
    targetId: 40,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS,
  },
  {
    id: 29,
    sourceId: 38,
    targetId: 42,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS_ATAU_TEMPUH_BERSAMA,
  },
  {
    id: 30,
    sourceId: 8,
    targetId: 30,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS_ATAU_TEMPUH_BERSAMA,
  },
  {
    id: 31,
    sourceId: 21,
    targetId: 30,
    relationType: EDGE_RELATION_TYPES.PRASYARAT_LULUS_ATAU_TEMPUH_BERSAMA,
  },
];
